# GAME
GAME_TITLE = "Spanish Game"
FRAMES_PER_SECOND = 60
PATH_TO_BASE = "words/words.csv"
PATH_TO_ICON = 'graphics/icon.png'
PATH_TO_LEAD = 'leaderboards/leaderboards.csv'
PATH_TO_MAIN_FONT = 'font/Pixeltype.ttf'
PATH_TO_SETTINGS = 'settings/settings.txt'
PATH_TO_LIGHT_ON = 'graphics/light_on.png'
PATH_TO_LIGHT_OFF = 'graphics/light_off.png'
# SCREEN
SCREEN_SIZE = (800, 600)
# COLORS - BACKGROUND
BACKGROUND_COLOR = (237, 113, 75)
# COLORS - FONTS
NORMAL_COLOR = (64, 64, 64)
GOOD_COLOR = (30, 152, 66)
BAD_COLOR = (255, 0, 0)
MEDIUM_COLOR = (128, 64, 64)
# FONT_SIZE
MAIN_FONT_SIZE = 50
# WORD_INPUT_TEXTBOX
WORD_INPUT_SIZE = (250, 50)
WORD_INPUT_POS = (270, 400)
WORD_INPUT_ID = '#word_input'
# LIGHT
LIGHT_SIZE = (70, 70)
LIGHTS_NUM = 6
LIGHT_POS = [(300, 100), (300, 200), (300, 300), (400, 100), (400, 200), (400, 300)]
# SCOREBOARD
SCOREBOARD_POS = (680, 20)
SCOREBOARD_LIMIT = 999
# TIMER
TIMER_POS = (400, 30)
TIMER_WORD_LIMIT = 10
# WORD_BASE
WORD_POS = (400, 80)
# COMMENT
COMMENT_POS = (400, 500)
# EXIT_HINT
EXIT_HINT_POS = (160, 580)
EXIT_HINT_TEXT = 'Wcisnij ESC by wyjsc'
# LEADERBOARD_TEXTBOX
LEAD_TEXTBOX_SIZE = (250, 50)
LEAD_TEXTBOX_POS = (270, 400)
LEAD_TEXTBOX_ID = '#lead_textbox'
# LEADERBOARDS_HINT
LEAD_HINT_POS = (380, 500)
LEAD_HINT_TEXT = 'Wpisz swoj nick i wcisnij ENTER'
# GAME_BUTTON
GAME_BUTTON_TEXT = 'GRAJ'
GAME_BUTTON_POS = (350, 200)
GAME_BUTTON_SIZE = (120, 50)
GAME_BUTTON_ID = '#game_button'
# LEADERBOARD_BUTTON
LEAD_BUTTON_TEXT = 'WYNIKI'
LEAD_BUTTON_POS = (350, 300)
LEAD_BUTTON_SIZE = (120, 50)
LEAD_BUTTON_ID = '#lead_button'
# SETTINGS_BUTTON
SETTINGS_BUTTON_TEXT = 'OPCJE'
SETTINGS_BUTTON_POS = (350, 400)
SETTINGS_BUTTON_SIZE = (120, 50)
SETTINGS_BUTTON_ID = '#settings_button'
# LEADERBOARDS_TEXT
LEAD_TXT_POS = (350, 280)
# TIME_SLIDER
TIME_SLIDER_POS = (250, 70)
TIME_SLIDER_SIZE = (300, 50)
TIME_SLIDER_START_VAL = 10
TIME_SLIDER_RANGE = (3, 20)
TIME_SLIDER_ID = '#time_slider'
# TIME_SLIDER_TEXT
TIME_SLIDER_TEXT_POS = (400, 50)
TIME_SLIDER_TEXT = 'CZAS NA ODPOWIEDZ [s]: '
# LEADERBOARDS
LEAD_N_SHOW = 15
# VOL_SLIDER
VOL_SLIDER_POS = (250, 170)
VOL_SLIDER_SIZE = (300, 50)
VOL_SLIDER_START_VAL = 100
VOL_SLIDER_RANGE = (0, 100)
VOL_SLIDER_ID = '#volume_slider'
# VOL_SLIDER_TEXT
VOL_SLIDER_TEXT_POS = (400, 150)
VOL_SLIDER_TEXT = 'GLOSNOSC: '
# ACCENT_SELECT
ACCENT_SELECT_POS = (250, 270)
ACCENT_SELECT_SIZE = (300, 66)
ACCENT_SELECT_ID = '#accent_select'
ACCENT_CHECKING_OPTIONS = ['NIE', 'TAK (0.5 POINT JESLI BRAK AKCENTU)', 'TAK']
# ACCENT_SELECT_TEXT
ACCENT_TEXT_POS = (400, 250)
ACCENT_TEXT = 'SPRAWDZANIE AKCENTOW: '
# LANG_SELECT_TEXT
LANG_TEXT_POS = (400, 370)
LANG_TEXT = 'JEZYK SLOWA NA EKRANIE: '
# LANG_SELECT
LANG_SELECT_POS = (250, 390)
LANG_SELECT_SIZE = (300, 46)
LANG_SELECT_ID = '#lang_select'
LANG_SELECT_OPTIONS = ['POLSKI', 'HISZPANSKI']
# CLEAR_LEAD_BUTTON
CLEAR_LEAD_BUTTON_TEXT = 'RESETUJ WYNIKI'
CLEAR_LEAD_BUTTON_POS = (550, 500)
CLEAR_LEAD_BUTTON_SIZE = (200, 50)
CLEAR_LEAD_BUTTON_ID = '#clear_lead_button'
# CORRECT_SETTING_TEXT
CORRECT_SETTING_TEXT_POS = (400, 470)
CORRECT_SETTING_TEXT = 'POKAZ PRAWIDLOWA ODPOWIEDZ: '
# CORRECT_TEXT
CORRECT_TEXT_POS = (400, 470)
CORRECT_TEXT = 'PRAWIDLOWA ODPOWIEDZ: '
# CORRECT_SELECT
CORRECT_SELECT_POS = (250, 490)
CORRECT_SELECT_SIZE = (300, 46)
CORRECT_SELECT_ID = '#correct_select'
CORRECT_SELECT_OPTIONS = ['TAK', 'NIE']
# DEFAULT_SETTINGS
DEFAULT_ACCENT = ACCENT_CHECKING_OPTIONS[0]
DEFAULT_VOLUME = 100
DEFAULT_TIME_ANSWER = 10
DEFAULT_LANG = 'POLSKI'
DEFAULT_SHOW = 'TAK'
# SUBSTITUTES
SUBST_FONT = 'arial'
